@apiURL = http://localhost:4001/api/v1
#####create new user
####
POST {{apiURL}}/auth/register
Content-Type: application/json

{
  "fname": "prasika",
  "lname": "adhikari",
  "email": "prashikauser@gmail.com",
  "phone": "1234",
  "password": "12345",
  "cpassword": "12345"
}


###

POST {{apiURL}}/auth/login
Content-Type: application/json

{
  "email": "prasikauser@gmail.com", 
  "password": "12345"

}

###
GET {{apiURL}}/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZXBnaEBnbWFpbC5jb20iLCJsbmFtZSI6ImRlZXBnaCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1OTc1MTg0MiwiZXhwIjoxNzYwMzU2NjQyfQ.ygb6RgbI9tBUkm7bHunkLmf6CnkiXeMUqnskQ6lF1bg

{

}

###
 GET {{apiURL}}/category
Content-Type: application/json

{
  
}

#####
POST {{apiURL}}/products
Content-Type: application/json

{
  "name": "Nokia Lumia",
  "description": "Ancient Beast",
  "price": 300,
  "stock": 3,
  "category": "68c8f01555ede480a0121d5e",
  "images": ["https://msblogs.thesourcemediaassets.com/2013/08/5543.Lumia925Blk34Combo3ATT_5F00_LR_5F00_1CC4F241.jpg", "https://cdn.mos.cms.futurecdn.net/irLuBqtehijKJiyd8DWum8.jpg"],
  "speacility": "Doesnt break at all"
}


#####
GET {{apiURL}}/products

#####
GET {{apiURL}}/products/featured-products



#####
#### Update product
PATCH {{apiURL}}/products
Content-Type: application/json

{
  "id": "68cfbe279b2684f7f1118e28", 
  "description": "Phone is now discontinued."
}


#####
#### Delete product
DELETE {{apiURL}}/products
Content-Type: application/json

{
  "id": "68cfbe279b2684f7f1118e28"
}

#####
#### place order
POST {{apiURL}}/orders
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZXBnaEBnbWFpbC5jb20iLCJsbmFtZSI6ImRlZXBnaCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc2MTAwNjY5OSwiZXhwIjoxNzYxNjExNDk5fQ.DA9poQwQzoaasaufuS1BlLMBMVYzXo6JMYykV0wctuA

{
  "customerId": "68e3ae95b4f266fd9bec046f",
  "items": [
    
    {
      "productId": "68f089010723bca18e2b373e",
      "productName":"Macbook",
      "quantity":2,
      "price": 2400,
      "currency":"AUD"
    }
  ],
  "total":2400
}


#####
#### get my all orders
GET {{apiURL}}/order?id=68e45e91d2c77b22c1fa493e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckBnbWFpbC5jb20iLCJmbmFtZSI6IlRlc3QiLCJsbmFtZSI6InRlc3QiLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjA1MjIxMzcsImV4cCI6MTc2MTEyNjkzN30.jIVGPJUP7vgVRG0TBB_rMgTc1o-Td2tHg25VKU5zUEg

###### get featured products
GET {{apiURL}}/products/featured-products
Content-Type: application/json


### send review
POST {{apiURL}}/reviews
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZXBnaEBnbWFpbC5jb20iLCJsbmFtZSI6ImRlZXBnaCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc2MTAwNzEwMiwiZXhwIjoxNzYxNjExOTAyfQ.lLsu005ql3t4mUcMQxElqIDtcOcB166inXpYaH4Qyfw

{
  "productId":"68f095ba7ecf14b3cef72a2b",
  "title":"Nice kkkkkkkkk phone",
  "rating":2,
  "comment":"Awesome phone"
}
###### get product details of subcategory
GET {{apiURL}}/category/vlogging
Content-Type: application/json


### 1️⃣ Signup (create new user)
POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
  "fname": "rena",
  "lname": "Adhik",
  "email": "rina1@gmail.com",
  "password": "12345",
  "phone": "1234567890",
   "cpassword": "12345"
 
}

###  Login (to verify signup)
POST http://localhost:4001/api/auth/login
Content-Type: application/json

{
  "email": "rina1@gmail.com",
  "password": "12345"
}

###  Forgot Password (send reset link)
POST http://localhost:4001/api/auth/forgot-password
Content-Type: application/json

{
  "email": "rina1@gmail.com"
}

###  Reset Password (replace <TOKEN> with actual token from email)
POST http://localhost:4001/api/auth/reset-password
Content-Type: application/json

{
  "email": "rami@gmail.com",
  "token": "",
  "newPassword": "NewPassword123"
}

###  Login with new password 
POST http://localhost:4001/api/auth/login
Content-Type: application/json

{
  "email": "prasika@gmail.com",
  "password": "NewPassword123"
}
###  Verify Email
POST   http://localhost:4001/api/auth/verify-email
Content-Type: application/json

{
  "email": "rami@gmail.com",
  "token": "YOUR_VERIFICATION_TOKEN"
}
